MAIN_PAGE_RECORDS_LIMIT = 6

INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 64

INGREDIENT_MIN_AMOUNT_IN_RECIPE = 1

RECIPE_NAME_MAX_LENGTH = 256
RECIPE_MIN_COOKING_TIME = 1
RECIPE_IMAGE_UPLOAD_TO = "recipes/"

MAX_EMAIL_LENGTH = 254
MAX_LOGIN_LENGTH = 150
LOGIN_REGEX_PATTERN = r"(?!me\b)(^[\w.@+-]+\Z)"
MAX_FIRSTNAME_LENGTH = 150
MAX_LASTNAME_LENGTH = 150
PROFILE_IMAGE_FOLDER = "users/"

INGREDIENT_INLINE_MIN_AMOUNT = 1