# Настройки пагинации
PAGINATION_DEFAULT_LIMIT = 6

# Ограничения для ингредиентов
INGREDIENT_TITLE_MAX_LEN = 128
INGREDIENT_MEASUREMENT_MAX_LEN = 64
INGREDIENT_MIN_QUANTITY = 1
INGREDIENT_RECIPE_MIN_AMOUNT = 1

# Ограничения для рецептов
RECIPE_TITLE_MAX_LEN = 256
RECIPE_MIN_PREP_MINUTES = 1
RECIPE_IMAGE_STORAGE_PATH = "recipes/"

# Ограничения для пользователей
USER_EMAIL_MAX_LEN = 254
USER_USERNAME_MAX_LEN = 150
USERNAME_VALIDATION_REGEX = r"(?!me\b)(^[\w.@+-]+\Z)"
USER_FIRST_NAME_MAX_LEN = 150
USER_LAST_NAME_MAX_LEN = 150
USER_AVATAR_STORAGE_PATH = "users/"